export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_REQUEST_SUCCESS = 'PRODUCT_LIST_REQUEST_SUCCESS';
export const PRODUCT_LIST_REQUEST_FAILURE = 'PRODUCT_LIST_REQUEST_FAILURE';

export const PRODUCT_INFO_REQUEST = 'PRODUCT_INFO_REQUEST';
export const PRODUCT_INFO_REQUEST_SUCCESS = 'PRODUCT_INFO_REQUEST_SUCCESS';
export const PRODUCT_INFO_REQUEST_FAILURE = 'PRODUCT_INFO_REQUEST_FAILURE';

export const CART_ADD = 'CART_ADD'
export const CART_REMOVE = 'CART_REMOVE'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_REQUEST_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_REQUEST_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_REQUEST_FAIL = 'USER_DETAILS_FAIL'


